### ISSUE TITLE
레시피 1-1 STS로스프링 메플리케이션 빌드하기

### ISSUE THREAD

**Issue by doubleseven** [dalman7/springRecipeStudy#1]
## 레시피 1-1 STS로스프링 메플리케이션 빌드하기 .
* TBD

**Comment by caleb940** [comment]
### **레시피 1-1 STS로 스프링 애플리케이션 빌드하기**
1. STS 설치
 https://spring.io/tools
 - 퇴근 시간에 칠칠이 알려줘서 정리할 시간이 없었음..
 - 2시간 걸려 집에 와서 너무 피곤해 씻고 잠시 누워있었음. 
   매일 한 챕터씩 할 수 있을 지 모르겠음..
   실습위주로 하면 너무 시간이 오래걸릴듯. 책의 구성이 나같은 초보위주가 아닌 어느정도 지식이 있는 대상을 위주로 하고 있는듯.. 

2. 프로젝트 생성
 - 회사서 메이븐을 사용하지만 책에서는 그레이들로 한다니 뭐, 불만없음

결론
 - 그냥 막연히 책 한 권 주욱 같이 읽는 수준으로 하면 되지 않을까 했는데... 그게 아니네.
   실습없이 책만 겉핥기 식으로 읽어서는 안될듯.. 이걸 같이 할 수 있을지 의문스러움.
   시간도 내기 쉽지 않을 거 같고(실습 위주로 해야 할 거 같아서.)
