### ISSUE TITLE
레시피 1-2 인텔리제이로 스프링애플리케이션 빌드하기

### ISSUE THREAD

**Issue by doubleseven** [dalman7/springRecipeStudy#2]
## 레시피 1-2 인텔리제이로 스프링애플리케이션 빌드하기
* spring project 생성하기
    - File > New > Project ...> Spring
    - 하지만 그 어느 누구도 이렇게 Spring Project 를 만들지는 않을 것이다. 
    - 실제로 Spring 프로젝트를 세팅하기 위해서는 Spring Boot 를 사용한다.
         * File > New > Project ...> Spring Initializer 를 이용한다.
    - 뭐 Spring Boot 가 정말 죽기보다 싫고 그냥 Spring 만 쓰고자 한다면 책에서처럼 할 수도 있을 것 같지만.. 

* maven 
    - 앞으로 maven 을 쓸 일은 별로 없어 보인다.
    - 실제 책에서도 maven 으로 구성된 샘플이 단 하나뿐이라고 말 해 준다. 
    - 그러므로 maven 을 따로 볼 필요는 없어 보인다. 
    - 그럼에도 library 에 대한 repository 는 maven repository 를 주로 사용하기 때문에 기본적으로 알고 있어야 하는 사항에 대해서는 습득할 필요가 있다.
    - 적어도 maven 의 pom 구성이 의미하는 것에 대해서는 알고 있어야 한다.

* gradle
    - 요즘 spring boot 를 사용해서 새로 생성되는 프로젝트는 gradle 로 구성된 경우가 많다.
    - 게다가 groovy 기반으로 구성된 gradle 이 급속도로 kotlin 기반으로 구성된 스크립트로 옮겨가는 듯 하다.
    - 따라서 가급적이면 kotlin 기반으로 익혀 두는 편이 좋다고 판단된다. (아쉽게도 대부분은 groovy 로 되어 있고 spring boot 로 생성된 프로젝트도 groovy 로 되어 있다. 하지만 욕심을 내서 kotlin 으로 변경해 보는 것을 추천하고 싶다.)
    - https://gradle.org/

* 결론
     - 사실 별로 정리할 내용이 없는 부분이다.
     - IntelliJ 개발 환경이 아니고 eclipse 로 개발을 해야 한다면 본 레시피는 걍 넘어가자. 
     - 하지만 회사에서 안 사준다면 개인돈을 들여서라도 IntelliJ 로 갈아타라고 권해주고 싶다.
     - 그냥 내용한 번 살펴본 것으로 만족하자

**Comment by caleb940** [comment]
Java 버전은 몇으로 할까요?

**Comment by doubleseven** [comment]
@caleb940 업무에 바로 써먹으려면 8, 앞으로 공부를 위해서라면 11 이 좋을 것 같아요
